//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1Part2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Game
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public System.DateTime GameDate { get; set; }
        public string Description { get; set; }
        public int ScoreOfTeamA { get; set; }
        public int ScoreOfTeamB { get; set; }
        public string WinningTeam { get; set; }
    }
}
